[build]
  publish = "."

# Убираем редирект с / на track.html
# [[redirects]]
#   from = "/"
#   to = "/track.html"
#   status = 200

# Оставляем только CORS для temp_data
[[headers]]
  for = "/temp_data/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=3600"
